### ISSUE TITLE
Running calendar standalone with different server

### ISSUE THREAD

**Issue by gary094** [nibdo/bloben-calendar#85]
Hi, is it possible at all to run bloben-calendar standalone with a different server?
I do already run a caldav server (radicale) and since I liked the UI of bloben I was thinking to give it a try.

I was trying to run docker-compose.yml with only the client part like this:

```
version: '3.8'

services:
  bloben:
    image: 'bloben/app:latest'
    container_name: bloben
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - '127.0.0.1:8081:80'
    restart: always
```

And my `.env` looks like this:

```
SKIP_PREFLIGHT_CHECK=true
REACT_APP_VERSION=$npm_package_version
REACT_APP_NODE_ENV=production
NODE_ENV=production
```

But still I receive some errors upon startup:

```
022-07-20T09:45:16: PM2 log: App [index:0] exited with code [0] via signal [SIGINT]
2022-07-20T09:45:16: PM2 log: App [index:0] starting in -fork mode-
2022-07-20T09:45:16: PM2 log: App [index:0] online
Error: Missing required env: NODE_ENV
    at /usr/app/api/src/config/env.ts:62:13
    at /usr/app/api/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/usr/app/api/node_modules/lodash/lodash.js:3032:24)
    at /usr/app/api/node_modules/lodash/lodash.js:4936:18
    at forEach (/usr/app/api/node_modules/lodash/lodash.js:9410:14)
    at validateRequiredEnvs (/usr/app/api/src/config/env.ts:60:10)
    at loadEnv (/usr/app/api/src/config/env.ts:69:3)
    at /usr/app/api/src/index.ts:27:18
    at Generator.next (<anonymous>)
    at /usr/app/api/build/index.js:8:71
TypeError: Cannot read properties of undefined (reading 'nodeEnv')
    at Object.error (/usr/app/api/src/utils/logger.ts:48:13)
    at /usr/app/api/src/index.ts:46:12
    at Generator.next (<anonymous>)
    at /usr/app/api/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/app/api/build/index.js:4:12)
    at startServer (/usr/app/api/src/index.ts:24:54)
    at Object.<anonymous> (/usr/app/api/src/index.ts:54:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
```

Now is what I am trying to do possible at all?

**Comment by nibdo** [comment]
Hello, sorry, but this is not possible. At least not without very heavy modifications. But of course you can connect bloben to your radicale server, but you will need all parts. Bloben is not caldav server like baikal or radicale.

**Comment by gary094** [comment]
Okay I see thanks!
